#include <windows.h>
#include <setupapi.h>
#include <cfgmgr32.h>
#include <bluetoothapis.h>
#include <sddl.h>
#include <wincrypt.h>
#include <shlobj.h>
#include <filesystem>
#include <fstream>
#include <sstream>
#include <iomanip>
#include <vector>
#include <string>
#include <map>
#include <mutex>
#include <thread>
#include <atomic>
#include <chrono>
#include <algorithm>
#include <cctype>
#include "security.cpp"

#pragma comment(lib, "advapi32.lib")
namespace fs=std::filesystem; using namespace std::chrono_literals;
static const wchar_t* SERVICE_NAME=L"BLESync"; static SERVICE_STATUS_HANDLE g_sh; static SERVICE_STATUS g_ss{}; static std::atomic<bool> g_stop=false;
struct Config { fs::path exe, storage; int interval=5; std::wstring level=L"INFO"; };
static std::wstring trim(std::wstring s){while(!s.empty()&&iswspace(s.front()))s.erase(s.begin());while(!s.empty()&&iswspace(s.back()))s.pop_back();return s;}
static std::wstring lower(std::wstring s){std::transform(s.begin(),s.end(),s.begin(),towlower);return s;}
static bool admin(){BOOL b=FALSE; PSID sid=nullptr; SID_IDENTIFIER_AUTHORITY a=SECURITY_NT_AUTHORITY; if(AllocateAndInitializeSid(&a,2,SECURITY_BUILTIN_DOMAIN_RID,DOMAIN_ALIAS_RID_ADMINS,0,0,0,0,0,0,&sid)) {CheckTokenMembership(nullptr,sid,&b);FreeSid(sid);} return b;}
static fs::path module(){wchar_t b[32768];DWORD n=GetModuleFileNameW(nullptr,b,32768);return fs::path(std::wstring(b,n));}
static Config load_config(){Config c; c.exe=module().parent_path(); std::wifstream f(c.exe/L"BLESync.ini"); f.imbue(std::locale("")); std::wstring l; while(std::getline(f,l)){l=trim(l);if(l.empty()||l[0]==L';'||l[0]==L'#'||l[0]==L'[')continue;auto p=l.find(L'=');if(p==std::wstring::npos)continue;auto k=lower(trim(l.substr(0,p))),v=trim(l.substr(p+1));if(k==L"storagepath")c.storage=fs::path(v);else if(k==L"scaninterval"){try{c.interval=std::max(1,std::stoi(v));}catch(...){}}else if(k==L"loglevel")c.level=v;}if(c.storage.empty())c.storage=c.exe/L"BLESyncData";return c;}
class Log {std::mutex m;fs::path p;std::wstring level;public:void init(const Config&c){level=c.level;p=c.storage/L"logs"/L"BLESync.log";std::error_code e;fs::create_directories(p.parent_path(),e);}void put(const wchar_t*lv,const std::wstring&s){std::lock_guard<std::mutex>g(m);std::wofstream f(p,std::ios::app);f.imbue(std::locale(""));if(f){SYSTEMTIME t;GetLocalTime(&t);f<<L"["<<std::setfill(L'0')<<std::setw(2)<<t.wHour<<L":"<<std::setw(2)<<t.wMinute<<L":"<<std::setw(2)<<t.wSecond<<L"] ["<<lv<<L"] "<<s<<L"\n";}}} g_log;
static std::wstring hex(const BYTE*d,DWORD n){std::wstringstream s;for(DWORD i=0;i<n;i++)s<<std::hex<<std::setw(2)<<std::setfill(L'0')<<(int)d[i];return s.str();}
struct V {DWORD type=0;std::vector<BYTE> data;}; using Values=std::map<std::wstring,V>; struct K {std::wstring name;Values vals;std::vector<K> sub;};
static bool read_tree(HKEY h,K&k){DWORD n=0,m=0;RegQueryInfoKeyW(h,nullptr,nullptr,nullptr,&n,&m,nullptr,nullptr,nullptr,nullptr,nullptr,nullptr);for(DWORD i=0;i<m;i++){wchar_t name[512];DWORD nl=512,type=0,sz=0;if(RegEnumValueW(h,i,name,&nl,nullptr,&type,nullptr,&sz)!=ERROR_SUCCESS)continue;V v;v.type=type;v.data.resize(sz);nl=512;if(RegEnumValueW(h,i,name,&nl,nullptr,&v.type,v.data.data(),&sz)==ERROR_SUCCESS){v.data.resize(sz);k.vals[name]=std::move(v);}}for(DWORD i=0;i<n;i++){wchar_t name[512];DWORD nl=512;if(RegEnumKeyExW(h,i,name,&nl,nullptr,nullptr,nullptr,nullptr)!=ERROR_SUCCESS)continue;HKEY ch;if(RegOpenKeyExW(h,name,0,KEY_READ|KEY_WOW64_64KEY,&ch)!=ERROR_SUCCESS)continue;K q;q.name=name;read_tree(ch,q);RegCloseKey(ch);k.sub.push_back(std::move(q));}return true;}
static void write_u32(std::ofstream&f,uint32_t x){f.write((char*)&x,4);}static bool read_u32(std::ifstream&f,uint32_t&x){return !!f.read((char*)&x,4);}static void ws(std::ofstream&f,const std::wstring&s){write_u32(f,(uint32_t)s.size());f.write((char*)s.data(),s.size()*2);}static bool rs(std::ifstream&f,std::wstring&s){uint32_t n;if(!read_u32(f,n)||n>100000)return false;s.resize(n);return !!f.read((char*)s.data(),n*2);}
static void save_k(std::ofstream&f,const K&k){ws(f,k.name);write_u32(f,(uint32_t)k.vals.size());for(auto&[n,v]:k.vals){ws(f,n);write_u32(f,v.type);write_u32(f,(uint32_t)v.data.size());if(!v.data.empty())f.write((char*)v.data.data(),v.data.size());}write_u32(f,(uint32_t)k.sub.size());for(auto&q:k.sub)save_k(f,q);}
static bool load_k(std::ifstream&f,K&k){uint32_t n; if(!rs(f,k.name)||!read_u32(f,n)||n>100000)return false; for(uint32_t i=0;i<n;i++){std::wstring name;V v;uint32_t type=0,size=0;if(!rs(f,name)||!read_u32(f,type)||!read_u32(f,size)||size>100000000)return false;v.type=type;v.data.resize(size);if(size&&!f.read((char*)v.data.data(),size))return false;k.vals[name]=std::move(v);}if(!read_u32(f,n)||n>100000)return false;for(uint32_t i=0;i<n;i++){K q;if(!load_k(f,q))return false;k.sub.push_back(std::move(q));}return true;}
static bool snapshot(const Config&c,const wchar_t*root,const fs::path&out,K&tree){HKEY h;if(RegOpenKeyExW(HKEY_LOCAL_MACHINE,root,0,KEY_READ|KEY_WOW64_64KEY,&h)!=ERROR_SUCCESS)return false;tree.name=root;read_tree(h,tree);RegCloseKey(h);std::error_code e;fs::create_directories(out.parent_path(),e);auto tmp=out;tmp+=L".tmp";std::ofstream f(tmp,std::ios::binary|std::ios::trunc);if(!f)return false;f.write("BLESNAP1",8);write_u32(f,1);save_k(f,tree);f.flush();f.close();if(!MoveFileExW(tmp.c_str(),out.c_str(),MOVEFILE_REPLACE_EXISTING|MOVEFILE_WRITE_THROUGH)){DeleteFileW(tmp.c_str());return false;}return true;}
static bool load_snapshot(const fs::path&p,K&k){std::ifstream f(p,std::ios::binary);char h[8];uint32_t ver;if(!f.read(h,8)||memcmp(h,"BLESNAP1",8)||!read_u32(f,ver)||ver!=1)return false;return load_k(f,k);}
static bool same(const K&a,const K&b){if(a.vals.size()!=b.vals.size()||a.sub.size()!=b.sub.size())return false;for(auto&[n,v]:a.vals){auto i=b.vals.find(n);if(i==b.vals.end()||v.type!=i->second.type||v.data!=i->second.data)return false;}for(size_t i=0;i<a.sub.size();i++)if(a.sub[i].name!=b.sub[i].name||!same(a.sub[i],b.sub[i]))return false;return true;}
static bool radio(bool&known,bool&enabled){known=false;enabled=false;HBLUETOOTH_RADIO_FIND f;BLUETOOTH_FIND_RADIO_PARAMS p{sizeof(p)};HANDLE h=BluetoothFindFirstRadio(&p,&f);if(!h)return false;BLUETOOTH_RADIO_INFO i{};i.dwSize=sizeof(i);if(BluetoothGetRadioInfo(f,&i)==ERROR_SUCCESS){known=true;enabled=true;}BluetoothFindRadioClose(f);CloseHandle(h);return true;}
static SERVICE_STATUS_PROCESS svcstat(const wchar_t*n){SERVICE_STATUS_PROCESS s{};SC_HANDLE m=OpenSCManagerW(nullptr,nullptr,SC_MANAGER_CONNECT);if(!m)return s;SC_HANDLE h=OpenServiceW(m,n,SERVICE_QUERY_STATUS);if(h){DWORD z;QueryServiceStatusEx(h,SC_STATUS_PROCESS_INFO,(LPBYTE)&s,sizeof(s),&z);CloseServiceHandle(h);}CloseServiceHandle(m);return s;}
static bool install(){if(!admin())return false;Config c=load_config();SC_HANDLE m=OpenSCManagerW(nullptr,nullptr,SC_MANAGER_ALL_ACCESS);if(!m)return false;auto exe=(c.exe/L"BLESync.exe").wstring();SC_HANDLE s=OpenServiceW(m,SERVICE_NAME,SERVICE_ALL_ACCESS);if(!s)s=CreateServiceW(m,SERVICE_NAME,L"BLESync Bluetooth Persistence Service",SERVICE_ALL_ACCESS,SERVICE_WIN32_OWN_PROCESS,SERVICE_AUTO_START,SERVICE_ERROR_NORMAL,exe.c_str(),nullptr,nullptr,nullptr,L"LocalSystem",nullptr);if(!s){CloseServiceHandle(m);return false;}SERVICE_DELAYED_AUTO_START_INFO d{TRUE};ChangeServiceConfig2W(s,SERVICE_CONFIG_DELAYED_AUTO_START_INFO,&d);SC_ACTION a[3]={{SC_ACTION_RESTART,60000},{SC_ACTION_RESTART,120000},{SC_ACTION_RESTART,300000}};SERVICE_FAILURE_ACTIONSW fa{0, nullptr,nullptr,3,a};ChangeServiceConfig2W(s,SERVICE_CONFIG_FAILURE_ACTIONS,&fa);StartServiceW(s,0,nullptr);CloseServiceHandle(s);CloseServiceHandle(m);return true;}
static bool uninstall(){if(!admin())return false;SC_HANDLE m=OpenSCManagerW(nullptr,nullptr,SC_MANAGER_ALL_ACCESS);if(!m)return false;SC_HANDLE s=OpenServiceW(m,SERVICE_NAME,SERVICE_STOP|DELETE|SERVICE_QUERY_STATUS);if(!s){CloseServiceHandle(m);return true;}SERVICE_STATUS st{};ControlService(s,SERVICE_CONTROL_STOP,&st);bool ok=DeleteService(s);CloseServiceHandle(s);CloseServiceHandle(m);return ok;}
static void report(DWORD st,DWORD win=NO_ERROR,DWORD hint=0){g_ss.dwServiceType=SERVICE_WIN32_OWN_PROCESS;g_ss.dwCurrentState=st;g_ss.dwControlsAccepted=(st==SERVICE_RUNNING)?SERVICE_ACCEPT_STOP|SERVICE_ACCEPT_SHUTDOWN:0;g_ss.dwWin32ExitCode=win;g_ss.dwWaitHint=hint;SetServiceStatus(g_sh,&g_ss);}
static void worker(){Config c=load_config();g_log.init(c);std::error_code e;fs::create_directories(c.storage/L"registry",e);if(e){g_log.put(L"ERROR",L"Storage directory creation failed");return;}ProtectStorage(c.storage);g_log.put(L"INFO",L"Service worker started");K last;bool have=false;auto path=c.storage/L"registry"/L"devices.regdata";while(!g_stop){auto ss=svcstat(L"bthserv");bool known=false,en=false;radio(known,en);if(ss.dwCurrentState==SERVICE_START_PENDING||ss.dwCurrentState==SERVICE_STOP_PENDING){g_log.put(L"DEBUG",L"Bluetooth service pending; deferring synchronization");}else if(ss.dwCurrentState==SERVICE_RUNNING&&known&&en){K cur;if(snapshot(c,L"SYSTEM\\CurrentControlSet\\Services\\BTHPORT\\Parameters\\Devices",path,cur)){if(!have){last=cur;have=true;g_log.put(L"INFO",L"Initial Bluetooth registry snapshot captured");}else if(!same(last,cur)){last=cur;g_log.put(L"INFO",L"Bluetooth registry snapshot changed; persistent snapshot updated");}}}else if(!known||!en)g_log.put(L"DEBUG",L"Bluetooth radio unavailable or disabled; no restore or service control");for(int i=0;i<c.interval&&!g_stop;i++)std::this_thread::sleep_for(1s);}g_log.put(L"INFO",L"Service worker stopped");}
static void WINAPI ctrl(DWORD c){if(c==SERVICE_CONTROL_STOP||c==SERVICE_CONTROL_SHUTDOWN){g_stop=true;report(SERVICE_STOP_PENDING,NO_ERROR,5000);}}
static void WINAPI main_svc(DWORD,LPWSTR*){g_sh=RegisterServiceCtrlHandlerW(SERVICE_NAME,ctrl);if(!g_sh)return;report(SERVICE_START_PENDING,NO_ERROR,5000);std::thread t(worker);report(SERVICE_RUNNING);t.join();report(SERVICE_STOPPED);}
int wmain(int argc,wchar_t**argv){if(argc>1){auto a=lower(argv[1]);if(a==L"--install")return install()?0:1;if(a==L"--uninstall")return uninstall()?0:1;if(a==L"--console"){worker();return 0;}if(a==L"--capture"){Config c=load_config();K k;return snapshot(c,L"SYSTEM\\CurrentControlSet\\Services\\BTHPORT\\Parameters\\Devices",c.storage/L"registry"/L"devices.regdata",k)?0:1;}}SERVICE_TABLE_ENTRYW t[]={{const_cast<LPWSTR>(SERVICE_NAME),main_svc},{nullptr,nullptr}};if(!StartServiceCtrlDispatcherW(t))return GetLastError()==ERROR_FAILED_SERVICE_CONTROLLER_CONNECT? (worker(),0):1;return 0;}
